In [15]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr*2)
print(arr.shape)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]
(2, 5)


In [17]:
import pandas as pd
arr2 = pd.DataFrame(arr)
arr2

data = {'Name':["Alice","Bob"],
        "Age":[25,30]}
df = pd.DataFrame(data)
df

Name  Age
0  Alice   25
1    Bob   30

In [1]:
import pandas as pd
import numpy as np

data = {'Name':["Daya","Vishal","Saurabh","Mohit","Kullu"],
        'Age':[20,21,22,23,23],
        'Department':["CSE","ML","CE","ME","EE"],
        'Salary':[12000,34000,34000,56000,10000]}
df = pd.DataFrame(data)
df

print(df.head(3)) # Top 3 Rows
print(df[["Name","Salary"]]) # Two Individual Columns
print(df["Salary"].mean()) # Average of Salary
print(df[df["Salary"] == df["Salary"].max()]) # Tuple with Highest Salary
print(df["Salary"].std()) # Standard Deviation Of Salaries

data2 = np.array(df["Salary"])
print(data2)

      Name  Age Department  Salary
0     Daya   20        CSE   12000
1   Vishal   21         ML   34000
2  Saurabh   22         CE   34000
      Name  Salary
0     Daya   12000
1   Vishal   34000
2  Saurabh   34000
3    Mohit   56000
4    Kullu   10000
29200.0
    Name  Age Department  Salary
3  Mohit   23         ME   56000
18899.73544788392
[12000 34000 34000 56000 10000]
